spring:
  profiles:
    active: development
  mvc:
    message-codes-resolver:
      format: PREFIX_ERROR_CODE
    dispatch-options-request: true
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jackson:
    serialization:
      indent_output: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  #address: 192.169.1.1
  port: 9000
  ssl:
    enabled: false
  tomcat:
    accesslog:
      enabled: true

multipart:
  max-file-size: 10Mb
  max-request-size: 10mb

security:
  basic:
    enabled: false

logging:
  level:
    org:
      springframework:
        web: warn
        security: warn
        boot:
          autoconfigure:
            security: warn
    com:
      redparty:
        partyplanner: debug

#debug: true


--- ######### for development purpose #########


spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/party_planner?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate: warn

--- ######### for testing purpose #########


spring:
  profiles: testing
  datasource:
    url: jdbc:h2:mem:testDB;Mode=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    continue-on-error: true
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    org:
      springframework:
        test: warn
        jdbc: warn
      hibernate: warn
        #SQL: warn

